name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: icons    # Display icons instead of labels
          plugin_topics_limit: 30      # Disable limitations
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_limit: 8                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS"      # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15                         # Set maximum time for indepth analysis
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 375                               # Limit recently used stats to last week
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year                        # Display full year instead of half year
          commits_authoring: xavicaromiro@gmail.com                     # Surnames or email addresses used to identify your commits
          plugin_habits: yes
          plugin_habits_from: 200                                       # Use 200 events to compute habits
          plugin_habits_days: 30                                        # Keep only events from last 14 days
          plugin_habits_facts: yes                                      # Display facts section
          plugin_habits_charts: yes                                     # Display charts section
          plugin_habits_trim: yes                                       # Trim unused hours on daily chart
          config_timezone: Europe/Madrid                                # Set timezone
          plugin_followup: yes
          plugin_achievements: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_achievements_threshold: B      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: compact  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
